apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: chainmaker
  name: chainmaker-cert-pvc
  labels:
    app: chainmaker-console
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs-sc
---  
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chainmaker-console
  namespace: chainmaker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chainmaker-console
  template:
    metadata:
      labels:
        app: chainmaker-console
    spec:
      containers:
      - name: chainmaker-console
        image: richzhao/chainmaker-console:v2.3.1
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: chainmaker-cert-volume
          mountPath: /chainmaker/cert
        - name: chainmaker-console-config-volume
          mountPath: /chainmaker-console/configs
          readOnly: true
        - name: kube-config-volume
          mountPath: /root/.kube
          readOnly: true
        ports:
        - containerPort: 9999
      - name: chainmaker-console-web
        image: richzhao/chainmaker-console-web:v2.3.1
        ports:
        - containerPort: 80
      volumes:
      - name: chainmaker-cert-volume
        persistentVolumeClaim:
          claimName: chainmaker-cert-pvc
      - name: chainmaker-console-config-volume
        configMap:
          name: chainmaker-console-config
      - name: kube-config-volume
        configMap:
          name: kube-config
---
apiVersion: v1
kind: Service
metadata:
  name: chainmaker-console
  labels:
    app: chainmaker-console
  namespace: chainmaker
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      nodePort: 30280
      name: http
    - port: 9999
      targetPort: 9999
      protocol: TCP
      nodePort: 30299
      name: backend
  selector:
    app: chainmaker-console
