---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: testcmorg1-cmtestnode1-pvc
  namespace: chainmaker
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-chainmaker
  resources:
    requests:
      storage: 1Gi
---      
apiVersion: v1
kind: Pod
metadata:
  name: copy-pod
  namespace: chainmaker
spec:
  containers:
    - name: copy-container
      image: nginx
      command: ["sh", "-c", "cp -R /crypto/TestCMorg1-cmtestnode1/* /chainmaker-go/node/"]
      volumeMounts:
        - name: crypto-volume
          mountPath: /crypto 
        - name: node-config
          mountPath: /chainmaker-go/node
  volumes:
    - name: crypto-volume
      hostPath:
        path: /home/student/chainmaker # 修改为宿主机目录的实际路径
        type: ""    
    - name: node-config
      persistentVolumeClaim:
        claimName: testcmorg1-cmtestnode1-pvc      
---
apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  namespace: chainmaker
spec:
  containers:
  - name: copy-pod
    image: chainmakerofficial/chainmaker:v2.3.1
    imagePullPolicy: IfNotPresent
    # command: ["orderer"]
    command: ["sh", "-c", "sleep 48h"]
    volumeMounts:
      - name: node-config
        mountPath: /chainmaker/chainmaker-go/node1
  volumes:
    - name: node-config
      configMap: 
        name: node1-config

      # hostPath:
      #   path: /home/student/chainmaker/TestCMorg1-cmtestnode1