apiVersion: v1
kind: PersistentVolume
metadata:
  name: chainmaker-pv
  namespace: chainmaker
spec:
  storageClassName: nfs-sc
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  nfs: # 
    path: /srv/nfs4/k8s/chainmaker # nfs 服务端的共享目录
    server: 192.168.50.204 # nfs 服务端的 ip