---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    k8s.kuboard.cn/storageType: nfs_client_provisioner
  name: nfs-chainmaker
  resourceVersion: '3570'
parameters:
  archiveOnDelete: 'false'
provisioner: nfs-nfs-chainmaker
reclaimPolicy: Retain
volumeBindingMode: Immediate

---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations: {}
  labels:
    app: eip-nfs-nfs-chainmaker
  name: eip-nfs-nfs-chainmaker
  namespace: kube-system
  resourceVersion: '156525'
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: eip-nfs-nfs-chainmaker
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: eip-nfs-nfs-chainmaker
    spec:
      containers:
        - env:
            - name: PROVISIONER_NAME
              value: nfs-nfs-chainmaker
            - name: NFS_SERVER
              value: 192.168.50.204
            - name: NFS_PATH
              value: /srv/nfs4/k8s/chainmaker
          image: >-
            swr.cn-east-2.myhuaweicloud.com/kuboard-dependency/nfs-subdir-external-provisioner:v4.0.2
          imagePullPolicy: IfNotPresent
          name: nfs-client-provisioner
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /persistentvolumes
              name: nfs-client-root
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: eip-nfs-client-provisioner
      serviceAccountName: eip-nfs-client-provisioner
      terminationGracePeriodSeconds: 30
      volumes:
        - name: nfs-client-root
          persistentVolumeClaim:
            claimName: nfs-pvc-nfs-chainmaker
status:
  availableReplicas: 1
  conditions:
    - lastTransitionTime: '2023-08-05T12:17:16Z'
      lastUpdateTime: '2023-08-05T12:17:27Z'
      message: >-
        ReplicaSet "eip-nfs-nfs-chainmaker-dd955cc97" has successfully
        progressed.
      reason: NewReplicaSetAvailable
      status: 'True'
      type: Progressing
    - lastTransitionTime: '2023-08-07T04:51:27Z'
      lastUpdateTime: '2023-08-07T04:51:27Z'
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: 'True'
      type: Available
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1

---
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/bound-by-controller: 'yes'
  finalizers:
    - kubernetes.io/pv-protection
  name: nfs-pv-nfs-chainmaker
  resourceVersion: '3556'
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 10Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: nfs-pvc-nfs-chainmaker
    namespace: kube-system
    resourceVersion: '3552'
    uid: 289982c8-224f-4cdf-a4af-e7457692f2a0
  nfs:
    path: /srv/nfs4/k8s/chainmaker
    server: 192.168.50.204
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-storageclass-provisioner
  volumeMode: Filesystem
status:
  phase: Bound

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    pv.kubernetes.io/bind-completed: 'yes'
  finalizers:
    - kubernetes.io/pvc-protection
  name: nfs-pvc-nfs-chainmaker
  namespace: kube-system
  resourceVersion: '3559'
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: nfs-storageclass-provisioner
  volumeMode: Filesystem
  volumeName: nfs-pv-nfs-chainmaker
status:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 10Gi
  phase: Bound

