apiVersion: apps/v1
kind: Deployment
metadata:
  name: {orgid}-{nodename}
  namespace: chainmaker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {orgid}-{nodename}
  template:
    metadata:
      labels:
        app: {orgid}-{nodename}
    spec:
      initContainers:
      - name: init-cert
        image: busybox:1.28
        volumeMounts:
        - name: {orgid}-{nodename}-config-pvc
          mountPath: /chainmaker-go/config
        - name: chainmaker-cert-pvc
          mountPath: /chainmaker/cert
        command: ['sh', 'cp', "-r", "/chainmaker/cert/{orgid}", "/chainmaker-go/config/"]
      containers:
        - name: {orgid}-{nodename}
          image: "chainmakerofficial/chainmaker:v2.3.1"
          imagePullPolicy: IfNotPresent
          command: ["./chainmaker"]
          args: ["start", "-c", "/chainmaker-go/config/{orgid}/chainmaker.yml"]
          # command: ["sh", "-c", "sleep 48h"]
          ports:
            - name: libp2p
              containerPort: 11301
            - name: rpc
              containerPort: 12301
          volumeMounts:
            - name: {orgid}-{nodename}-data-pvc
              mountPath: /chainmaker-go/data
            - name: {orgid}-{nodename}-config-pvc
              mountPath: /chainmaker-go/config
            - name: {orgid}-{nodename}-log-pvc
              mountPath: /chainmaker-go/log
          - name: docker-go-container
            securityContext:
              privileged: true
            image: chainmakerofficial/chainmaker-vm-engine:v2.3.1
            resources:
              # limits:
                # cpu: "4"
                # memory: "8Gi"
              # requests:
                # cpu: "1"
                # memory: "2Gi"
            ports:
              - containerPort: 22351
                name: vmport
                protocol: TCP
            env:
              - name: CHAIN_RPC_PROTOCOL
                value: "1"
              - name: CHAIN_HOST
                value: "127.0.0.1"
              - name: CHAIN_RPC_PORT
                value: "22351"
              - name: SANDBOX_RPC_PORT
                value: "32351"
              - name: MAX_SEND_MSG_SIZE
                value: "100"
              - name: MAX_RECV_MSG_SIZE
                value: "100"
              - name: MAX_CONN_TIMEOUT
                value: "10"
              - name: MAX_ORIGINAL_PROCESS_NUM
                value: "20"
              - name: DOCKERVM_CONTRACT_ENGINE_LOG_LEVEL
                value: "DEBUG"
              - name: DOCKERVM_SANDBOX_LOG_LEVEL
                value: "DEBUG"
              - name: DOCKERVM_LOG_IN_CONSOLE
                value: "false"            
        volumes:
          - name: {orgid}-{nodename}-config-pvc
            persistentVolumeClaim:
              claimName: {orgid}-{nodename}-config-pvc
          - name: {orgid}-{nodename}-data-pvc
            persistentVolumeClaim:
              claimName: {orgid}-{nodename}-data-pvc    
          - name: {orgid}-{nodename}-log-pvc
            persistentVolumeClaim:
              claimName: {orgid}-{nodename}-log-pvc
          - name: chainmaker-cert-pvc
            persistentVolumeClaim:
              claimName: chainmaker-cert-pvc