---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: chainmaker
  name: {chainid}-{nodeid}-config-pvc
  labels:
    chainid: {chainid}
    nodeid: {nodeid}
    type: config
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Mi
  storageClassName: nfs-sc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: chainmaker
  name: {chainid}-{nodeid}-data-pvc
  labels:
    chainid: {chainid}
    nodeid: {nodeid}
    type: data
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs-sc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: chainmaker
  name: {chainid}-{nodeid}-log-pvc
  labels:
    chainid: {chainid}
    nodeid: {nodeid}
    type: log
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
  storageClassName: nfs-sc