---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: chainmaker
  name: {orgid}-{nodename}-config-pvc
  labels:
    orgid: {orgid}
    nodename: {nodename}
    type: config
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Mi
  storageClassName: nfs-sc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: chainmaker
  name: {orgid}-{nodename}-data-pvc
  labels:
    orgid: {orgid}
    nodename: {nodename}
    type: data
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs-sc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: chainmaker
  name: {orgid}-{nodename}-log-pvc
  labels:
    orgid: {orgid}
    nodename: {nodename}
    type: log
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
  storageClassName: nfs-sc