kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: chainmaker-chain1-pvc
  namespace: chainmaker
  annotations:
    kubesphere.io/creator: admin
    volume.beta.kubernetes.io/storage-provisioner: nfs/provisioner-229
    volume.kubernetes.io/storage-provisioner: nfs/provisioner-229
  finalizers:
    - kubernetes.io/pvc-protection
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: managed-nfs-storage
  volumeMode: Filesystem
---
metadata:
  annotations:
    k8s.kuboard.cn/pvcType: Dynamic
  name: chain1-node1-data-pvc
  namespace: chainmaker
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Mi
  storageClassName: managed-nfs-storage