apiVersion: batch/v1
kind: Job
metadata:
  name: create-certs
  namespace: fabric
spec:
  parallelism: 1
  completions: 1
  template:
    metadata:
      name: create-certs
    spec:
      volumes:
        - name: fabric-ca-volume
          persistentVolumeClaim:
            claimName: fabric-ca-pvc
        - name: fabric-scripts-volume
          configMap:
            name: fabric-scripts-cm
      containers:
        - name: create-certs
          image: hyperledger/fabric-ca:1.5.7
          resources:
            requests:
              memory: "300Mi"
              cpu: "300m"
            limits:
              memory: "500Mi"
              cpu: "350m"
          volumeMounts:
            - mountPath: /organizations
              name: fabric-ca-volume
              subPath: organizations
            - mountPath: /scripts
              name: fabric-scripts-volume
          command:
            - /bin/sh
            - -c
            - |
              bash ./scripts/orderer-certs.sh &&
              bash ./scripts/org1-certs.sh &&
              bash ./scripts/org2-certs.sh &&
              bash ./scripts/org3-certs.sh
      restartPolicy: Never
