GRANT ALL PRIVILEGES ON *.* TO 'webase'@'%' IDENTIFIED BY 'fisco-webase' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON *.* TO 'webase'@'%' IDENTIFIED BY 'fisco-webase' WITH GRANT OPTION;
FLUSH PRIVILEGES;