apiVersion: v1
kind: ConfigMap
metadata:
  name: node{i}.chainmaker
data:
  chainmaker.yml: |+
    auth_type: "permissionedWithCert" # [*]
    log:
      config_file: ../config/wx-org.chainmaker.org/log.yml
    crypto_engine: tjfoc #support gmssl, tencentsm and tjfoc
    blockchain:
      - chainId: chain1
        genesis: ../config/wx-org.chainmaker.org/chainconfig/bc1.yml
    node:
      org_id:            wx-org{i}.chainmaker.org  # [*]
      priv_key_file:     ../config/wx-org.chainmaker.org/certs/node/consensus1/consensus1.sign.key  # [*]
      cert_file:         ../config/wx-org.chainmaker.org/certs/node/consensus1/consensus1.sign.crt  # [*]
      cert_cache_size:   1000
      fast_sync:
        enabled: true  # [*]
      pkcs11:
        enabled: false  # [*]
        type: pkcs11
        library: /usr/local/lib64/pkcs11/libupkcs11.so
        label: HSM
        password: 11111111
        session_cache_size: 10
        hash: "SHA256"  # [*]
    sync:
      block_pool_size: 16
      conn_time_out_unit: 5000
    net:
      provider: LibP2P
      listen_addr: /ip4/0.0.0.0/tcp/11301
      max_peer_count_allow: 1000
      seeds:
        - "/dns/node1-headless.{namespace}.svc.cluster.local/tcp/11301/p2p/{seed_node_id}"
        - "/dns/node2-headless.{namespace}.svc.cluster.local/tcp/11301/p2p/{seed_node_id}"
        - "/dns/node3-headless.{namespace}.svc.cluster.local/tcp/11301/p2p/{seed_node_id}"
        - "/dns/node4-headless.{namespace}.svc.cluster.local/tcp/11301/p2p/{seed_node_id}"
      tls:
        enabled: true
        priv_key_file: ../config/wx-org.chainmaker.org/certs/node/consensus1/consensus1.tls.key
        cert_file: ../config/wx-org.chainmaker.org/certs/node/consensus1/consensus1.tls.crt
        priv_enc_key_file: ../config/wx-org.chainmaker.org/certs/node/consensus1/consensus1.tls.enc.key
        cert_enc_file: ../config/wx-org.chainmaker.org/certs/node/consensus1/consensus1.tls.enc.crt
    txpool:
      pool_type: "normal"
      max_txpool_size: 20000
      max_config_txpool_size: 10
      is_dump_txs_in_queue: true
      common_queue_num: 8
      batch_max_size: 100
      batch_create_timeout: 50
    rpc:
      provider: grpc  # [*]
      port: 12301
      check_chain_conf_trust_roots_change_interval: 60
      gateway:
        enabled: false
        max_resp_body_size: 16
      ratelimit:
        enabled: false
        type: 0
        token_per_second: -1
        token_bucket_size: -1
      subscriber:
        ratelimit:
          token_per_second: 100
          token_bucket_size: 100
      tls:
        mode:           twoway
        priv_key_file:  ../config/wx-org.chainmaker.org/certs/node/consensus1/consensus1.tls.key
        cert_file:      ../config/wx-org.chainmaker.org/certs/node/consensus1/consensus1.tls.crt
        priv_enc_key_file:  ../config/wx-org.chainmaker.org/certs/node/consensus1/consensus1.tls.enc.key
        cert_enc_file:      ../config/wx-org.chainmaker.org/certs/node/consensus1/consensus1.tls.enc.crt
      blacklist:
        addresses:
      max_send_msg_size: 100
      max_recv_msg_size: 100
    tx_filter:
      type: 0
      sharding:
        length: 5
        timeout: 60
        snapshot:
          type: 0
          timed:
            interval: 10
          block_height:
            interval: 10
          serialize_interval: 10
          path: ../data/wx-org.chainmaker.org/tx_filter
        birds_nest:
          length: 10
          rules:
            absolute_expire_time: 172800
          cuckoo:
            key_type: 1
            tags_per_bucket: 2
            bits_per_item: 11
            max_num_keys: 2000000
            table_type: 0
      birds_nest:
        length: 10
        snapshot:
          type: 0
          timed:
            interval: 10
          block_height:
            interval: 10
          serialize_interval: 10
          path: ../data/wx-org.chainmaker.org/tx_filter
        rules:
          absolute_expire_time: 172800
        cuckoo:
          key_type: 1
          tags_per_bucket: 2
          bits_per_item: 11
          max_num_keys: 2000000
          table_type: 0
    monitor:
      enabled: true
      port: 14321
    pprof:
      enabled: true
      port: 24321
    consensus:
      raft:
        snap_count: 10
        async_wal_save: true
        ticker: 1
    scheduler:
      rwset_log: false
    storage:
      store_path: ../data/wx-org.chainmaker.org/ledgerData1 # [*]
      unarchive_block_height: 300000
      archive_check_interval: 10
      restore_interval: 60
      disable_block_file_db: false
      logdb_segment_async: false
      logdb_segment_size: 128
      read_bfdb_timeout: 1000
      enable_bigfilter: false    #default false
      bigfilter_config:
        redis_hosts_port: "127.0.0.1:6300,127.0.0.1:6301"   #redis host:port
        redis_password: abcpass  #redis password
        tx_capacity: 1000000000   #support max transaction capacity
        fp_rate: 0.000000001      #false postive rate
      enable_rwc: true #default false
      rolling_window_cache_capacity: 55000 # greater than max_txpool_size*1.1
      write_block_type: 0  # 0 common write，1 quick write
      slow_log: 0
      disable_state_cache: false # default enable state cache
      state_cache_config:
        life_window: 3000000000000   #key/value ttl time, ns
        clean_window: 1000000000
        max_entry_size: 500
        hard_max_cache_size: 10240   #cache size MB
      blockdb_config:
        provider: leveldb # [*]
        leveldb_config:
          store_path: ../data/wx-org.chainmaker.org/block
      statedb_config:
        provider: leveldb
        leveldb_config:
          store_path: ../data/wx-org.chainmaker.org/state
      disable_historydb: false  # default enable history db
      historydb_config:
        provider: leveldb
        disable_key_history: false
        disable_contract_history: true
        disable_account_history: true
        leveldb_config:
          store_path: ../data/wx-org.chainmaker.org/history
      disable_resultdb: false
      resultdb_config:
        provider: leveldb
        leveldb_config:
          store_path: ../data/wx-org.chainmaker.org/result
      disable_contract_eventdb: true
      contract_eventdb_config:
        provider: sql
        sqldb_config:
          sqldb_type: mysql
          dsn: root:password@tcp(127.0.0.1:3306)/
    vm:
      go:
        enable: true
        data_mount_path: ../data/wx-org.chainmaker.org/go
        log_mount_path: ../log/wx-org.chainmaker.org/go
        protocol: tcp
        log_in_console: false
        log_level: INFO
        max_send_msg_size: 100
        max_recv_msg_size: 100
        dial_timeout: 10
        max_concurrency: 20
        runtime_server:
          port: 32351
        contract_engine:
          host: 127.0.0.1
          port: 22351
          max_connection: 5

