apiVersion: apps/v1
kind: Deployment
metadata:
  name: peer0-org3
  namespace: fabric
spec:
  selector:
    matchLabels:
      name: peer0-org3
  replicas: 1
  template:
    metadata:
      labels:
        name: peer0-org3
    spec:
      volumes:
        - name: fabric-ca-volume
          persistentVolumeClaim:
            claimName: fabric-ca-pvc
        - name: builders-config
          configMap:
            name: builders-config
            items:
              - key: core.yaml
                path: core.yaml
        - name: external-builder-detect
          configMap:
            name: builders-config
            items:
              - key: detect
                path: detect
                mode: 0544
        - name: external-builder-build
          configMap:
            name: builders-config
            items:
              - key: build
                path: build
                mode: 0544
        - name: external-builder-release
          configMap:
            name: builders-config
            items:
              - key: release
                path: release
                mode: 0544
      containers:
        - name: peer
          image: hyperledger/fabric-peer:2.4.1
          command: ["sh", "-c", "peer node start"]
          env:
            - name: CORE_PEER_ADDRESSAUTODETECT
              value: "true"
            - name: CORE_PEER_ID
              value: peer0-org3
            - name: CORE_PEER_ADDRESS
              value: peer0-org3:7051
            - name: CORE_PEER_LISTENADDRESS
              value: 0.0.0.0:7051
            - name: CORE_PEER_EVENTS_ADDRESS
              value: 0.0.0.0:7061
            - name: CORE_PEER_GOSSIP_BOOTSTRAP
              value: peer0-org3:7051
            - name: CORE_PEER_GOSSIP_ENDPOINT
              value: peer0-org3:7051
            - name: CORE_PEER_GOSSIP_EXTERNALENDPOINT
              value: peer0-org3:7051
            - name: CORE_PEER_GOSSIP_ORGLEADER
              value: "false"
            - name: CORE_PEER_GOSSIP_USELEADERELECTION
              value: "true"
            - name: CORE_PEER_PROFILE_ENABLED
              value: "true"
            - name: CORE_PEER_LOCALMSPID
              value: Org3MSP
            - name: CORE_PEER_MSPCONFIGPATH
              value: /organizations/peerOrganizations/org3.example.com/peers/peer0.org3.example.com/msp
            - name: FABRIC_LOGGING_SPEC
              value: debug
            - name: CORE_PEER_TLS_ENABLED
              value: "true"
            - name: CORE_PEER_TLS_CERT_FILE
              value: /organizations/peerOrganizations/org3.example.com/peers/peer0.org3.example.com/tls/server.crt
            - name: CORE_PEER_TLS_KEY_FILE
              value: /organizations/peerOrganizations/org3.example.com/peers/peer0.org3.example.com/tls/server.key
            - name: CORE_PEER_TLS_ROOTCERT_FILE
              value: /organizations/peerOrganizations/org3.example.com/peers/peer0.org3.example.com/tls/ca.crt
            - name: CORE_LEDGER_STATE_STATEDATABASE
              value: "CouchDB"
            - name: CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS
              value: "localhost:5984"
            - name: CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME
              value: admin
            - name: CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD
              value: adminpw
            - name: FABRIC_CFG_PATH
              value: /etc/hyperledger/fabric
            - name: CORE_OPERATIONS_LISTENADDRESS
              value: 0.0.0.0:9443
            - name: CORE_METRICS_PROVIDER
              value: prometheus
          ports:
            - containerPort: 7051
            - containerPort: 7052
            - containerPort: 7053
            - containerPort: 9443
          resources:
            limits:
              memory: "300Mi"
              cpu: "300m"
            requests:
              memory: "200Mi"
              cpu: "200m"
          volumeMounts:
            - mountPath: /opt/gopath/src/github.com/chaincode/
              name: fabric-ca-volume
              subPath: chaincode/
            - mountPath: /organizations
              name: fabric-ca-volume
              subPath: organizations
            - mountPath: /var/hyperledger/production
              name: fabric-ca-volume
              subPath: state/org3/peer0
            - mountPath: /etc/hyperledger/fabric/core.yaml
              name: builders-config
              subPath: core.yaml
            - mountPath: /builders/external/bin/detect
              name: external-builder-detect
              subPath: detect
            - mountPath: /builders/external/bin/build
              name: external-builder-build
              subPath: build
            - mountPath: /builders/external/bin/release
              name: external-builder-release
              subPath: release

        - name: couchdb
          image: couchdb:3.3.2
          resources:
            limits:
              memory: "300Mi"
              cpu: "300m"
            requests:
              memory: "200Mi"
              cpu: "200m"
          env:
            - name: COUCHDB_USER
              value: admin
            - name: COUCHDB_PASSWORD
              value: adminpw
          volumeMounts:
            - mountPath: /var/lib/couchdb
              name: fabric-ca-volume
              subPath: state/org3/peer0-couchdb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cli-peer0-org3
  namespace: fabric
spec:
  selector:
    matchLabels:
      name: cli-peer0-org3
  template:
    metadata:
      labels:
        name: cli-peer0-org3
    spec:
      volumes:
        - name: fabric-ca-volume
          persistentVolumeClaim:
            claimName: fabric-ca-pvc
        - name: fabric-scripts-volume
          configMap:
            name: fabric-scripts-cm
      containers:
        - name: cli-peer0-org3
          stdin: true
          tty: true
          resources:
            limits:
              memory: "300Mi"
              cpu: "200m"
            requests:
              memory: "200Mi"
              cpu: "90m"
          image: hyperledger/fabric-tools:2.4.1
          workingDir: /
          env:
            - name: ORDERER_CA
              value: /organizations/ordererOrganizations/example.com/orderers/orderer.example.com/msp/tlscacerts/tlsca.example.com-cert.pem

            - name: CORE_PEER_ADDRESS
              value: peer0-org3:7051
            - name: CORE_PEER_ID
              value: cli.peer0.org3.example.com
            - name: CORE_PEER_LOCALMSPID
              value: Org3MSP
            - name: CORE_PEER_MSPCONFIGPATH
              value: /organizations/peerOrganizations/org3.example.com/users/Admin@org3.example.com/msp
            - name: CORE_PEER_TLS_CERT_FILE
              value: /organizations/peerOrganizations/org3.example.com/peers/peer0.org3.example.com/tls/server.crt
            - name: CORE_PEER_TLS_ENABLED
              value: "true"
            - name: CORE_PEER_TLS_KEY_FILE
              value: /organizations/peerOrganizations/org3.example.com/peers/peer0.org3.example.com/tls/server.key
            - name: CORE_PEER_TLS_ROOTCERT_FILE
              value: /organizations/peerOrganizations/org3.example.com/peers/peer0.org3.example.com/tls/ca.crt
            - name: GOPATH
              value: /opt/gopath
            - name: SYS_CHANNEL
              value: system-channel
            - name: CORE_CHAINCODE_BUILDER
              value: hyperledger/fabric-ccenv:2.4.1
            - name: FABRIC_LOGGING_SPEC
              value: DEBUG
          volumeMounts:
            - mountPath: /organizations
              name: fabric-ca-volume
              subPath: organizations
            - mountPath: /configtx
              name: fabric-ca-volume
              subPath: configtx
            - mountPath: /channel-artifacts
              name: fabric-ca-volume
              subPath: channel-artifacts
            - mountPath: /scripts
              name: fabric-scripts-volume
            - mountPath: /opt/gopath/src/github.com/chaincode
              name: fabric-ca-volume
              subPath: chaincode
---
kind: Service
apiVersion: v1
metadata:
  name: peer0-org3
  namespace: fabric
  labels:
    app: peer0-org3
spec:
  selector:
    name: peer0-org3
  type: ClusterIP
  ports:
    - name: grpc
      port: 7051
      protocol: TCP
    - name: event
      port: 7061
      protocol: TCP
    - name: couchdb
      port: 5984
      protocol: TCP

---
#---------------- Peer0 org3 Metrics Service ---------------
apiVersion: v1
kind: Service
metadata:
  labels:
    app: peer0-org3
    metrics-service: "true"
  name: peer0-org3-metrics
  namespace: fabric
spec:
  type: ClusterIP
  ports:
    - name: "peer-metrics"
      port: 9443
      targetPort: 9443
  selector:
    name: peer0-org3
