---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    k8s.kuboard.cn/storageType: nfs_client_provisioner
    storageclass.kubernetes.io/is-default-class: 'true'
  name: chainmaker-nfs-sc
  resourceVersion: '672'
parameters:
  archiveOnDelete: 'false'
provisioner: nfs-nfs-sc
reclaimPolicy: Retain
volumeBindingMode: Immediate