---
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/bound-by-controller: 'yes'
  finalizers:
    - kubernetes.io/pv-protection
  name: chainmaker-pv
  namespace: chainmaker
  resourceVersion: '664'
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 20Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: nfs-pvc-nfs-sc
    namespace: kube-system
    resourceVersion: '661'
    uid: ae82334b-2166-448e-8977-4481fdd87255
  nfs:
    path: /srv/nfs4/k8s/chainmaker
    server: 192.168.50.204
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-storageclass-provisioner
  volumeMode: Filesystem