---
apiVersion: v1
kind: ConfigMap
metadata:
  name: testcmorg1-cmtestnode1-cm
  namespace: chainmaker
data:
  VERSION: v2.3.1
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: testcmorg1-cmtestnode1-pvc
  namespace: chainmaker
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-chainmaker
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: testcmorg1-cmtestnode1
  namespace: chainmaker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testcmorg1-cmtestnode1
  template:
    metadata:
      labels:
        app: testcmorg1-cmtestnode1
    spec:
      containers:
      - name: testcmorg1-cmtestnode1
        image: chainmakerofficial/chainmaker:v2.3.1
        imagePullPolicy: IfNotPresent
        # command: ["orderer"]
        command: ["sh", "-c", "sleep 48h"]
        envFrom:
          - configMapRef:
              name: testcmorg1-cmtestnode1-cm
        ports:
            - containerPort: 11060
            - containerPort: 12060
        volumeMounts:
          - name: node-config
            mountPath: /chainmaker-go/node
      volumes:
        - name: node-config
          persistentVolumeClaim:
            claimName: testcmorg1-cmtestnode1-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: testcmorg1-cmtestnode1-svc
  namespace: chainmaker
spec:
  type: ClusterIP
  selector:
    app: testcmorg1-cmtestnode1
  ports:
    - name: rpc
      port: 11060
      protocol: TCP
    - name: p2p
      port: 12060
      protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/proxy-connect-timeout: 60s
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
  labels:
    app: testcmorg1-cmtestnode1-igs
  name: testcmorg1-cmtestnode1-igs
  namespace: chainmaker
spec:
  ingressClassName: nginx
  rules:
    - host: testcmorg1-cmtestnode1.example.com
      http:
        paths:
          - backend:
              service:
                name: testcmorg1-cmtestnode1-svc
                port:
                  name: rpc
            path: /
            pathType: ImplementationSpecific      