apiVersion: apps/v1

kind: Deployment

metadata:
  name: nfs-client-provisioner

  labels:
    app: nfs-client-provisioner

  # replace with namespace where provisioner is deployed

  namespace: default

spec:
  replicas: 1

  strategy:
    type: Recreate

  selector:
    matchLabels:
      app: nfs-client-provisioner

  template:
    metadata:
      labels:
        app: nfs-client-provisioner

    spec:
      serviceAccountName: nfs-client-provisioner

      containers:
        - name: nfs-client-provisioner

          image: quay.io/external_storage/nfs-client-provisioner:latest

          volumeMounts:
            - name: nfs-client-root

              mountPath: /persistentvolumes

          env:
            - name: PROVISIONER_NAME

              value: nfs/provisioner-229

            - name: NFS_SERVER

              value: 192.168.50.204

            - name: NFS_PATH

              value: /srv/nfs4/k8s/chainmaker

      volumes:
        - name: nfs-client-root

          nfs:
            server: 192.168.50.204

            path: /srv/nfs4/k8s/chainmaker
