apiVersion: apps/v1 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: chaincode-basic-org1
  namespace: fabric
  labels:
    app: chaincode-basic-org1
spec:
  selector:
    matchLabels:
      app: chaincode-basic-org1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: chaincode-basic-org1
    spec:
      containers:
        - image: richzhao/basic-cc-hlf:1.0
          imagePullPolicy: IfNotPresent
          name: chaincode-basic-org1
          env:
            - name: CHAINCODE_ID
              value: "basic:6e007c5262903d1eb4f5c1a5ce1c47768ac7c12f33deca8edd2cf17c3b88f048"
            - name: CHAINCODE_SERVER_ADDRESS
              value: "0.0.0.0:7052"
          ports:
            - containerPort: 7052
---
apiVersion: v1
kind: Service
metadata:
  name: basic-org1
  namespace: fabric
  labels:
    app: basic-org1
spec:
  ports:
    - name: grpc
      port: 7052
      targetPort: 7052
  selector:
    app: chaincode-basic-org1
