apiVersion: apps/v1 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: chaincode-basic-org2
  namespace: fabric
  labels:
    app: chaincode-basic-org2
spec:
  selector:
    matchLabels:
      app: chaincode-basic-org2
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: chaincode-basic-org2
    spec:
      containers:
        - image: richzhao/basic-cc-hlf:1.0
          name: chaincode-basic-org2
          imagePullPolicy: IfNotPresent
          env:
            - name: CHAINCODE_ID
              value: "basic:94363004771a02d368064c34eea4c57d0149aa51b20a7ed429d8ebf0e14b7bb4"
            - name: CHAINCODE_SERVER_ADDRESS
              value: "0.0.0.0:7052"
          ports:
            - containerPort: 7052
---
apiVersion: v1
kind: Service
metadata:
  name: basic-org2
  namespace: fabric
  labels:
    app: basic-org2
spec:
  ports:
    - name: grpc
      port: 7052
      targetPort: 7052
  selector:
    app: chaincode-basic-org2
